Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,13 +40,18 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H myuniquesubdomain.loca.lt >> ~/.ssh/known_hosts
-          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v user@myuniquesubdomain.loca.lt "echo 'SSH connection successful'" || { echo 'SSH connection failed'; exit 1; }
+          ssh-keyscan -H 193.34.76.44 >> ~/.ssh/known_hosts
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v user@193.34.76.44 "echo 'SSH connection successful'" || { echo 'SSH connection failed'; exit 1; }
 
       - name: Deploy to server
         env:
           DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
         run: |
           echo "Starting deployment"
-          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v" ./ user@myuniquesubdomain.loca.lt:/path/to/deployment
+          mkdir -p ~/.ssh
+          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ls -la ~/.ssh  # تحقق من وجود المفتاح وأذوناته
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v user@193.34.76.44 "echo 'SSH connection successful'" || { echo 'SSH connection failed'; exit 1; }
+          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v" ./ user@193.34.76.44:/path/to/deployment
           echo "Deployment completed"
