Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,6 +67,8 @@ jobs:
         fi
         echo "File $file_path exists, reading content..."
         content=$(cat "$file_path")
+        
+        # التحقق من فتح و إغلاق وسوم PHP
         if [[ "$content" != *"<?php"* ]]; then
           echo "PHP opening tag not found."
           exit 1
@@ -75,6 +77,25 @@ jobs:
           echo "PHP closing tag not found."
           exit 1
         fi
+        
+        # التحقق من صحة الأقواس
+        if ! php -l "$file_path"; then
+          echo "PHP syntax check failed."
+          exit 1
+        fi
+        
+        # التحقق من وجود متغيرات معرفة
+        if ! grep -q "\$[a-zA-Z_][a-zA-Z0-9_]*\s*=" "$file_path"; then
+          echo "No variables defined."
+          exit 1
+        fi
+        
+        # التحقق من وجود الفواصل الصحيحة
+        if grep -q "[^;{}]\s*\n" "$file_path"; then
+          echo "Potential missing semicolon."
+          exit 1
+        fi
+        
         echo "Structural tests passed."
 
   run_custom_script:
@@ -130,7 +151,7 @@ jobs:
       run: |
         file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
         echo "Deploying to local server"
-        response=$(curl -X POST -F "file=@$file_path" https://aa94-92-253-226-113.ngrok-free.app/aqdevops/upload.php)
+        response=$(curl -X POST -F "file=@$file_path" https://c469-31-9-113-73.ngrok-free.app/aqdevops/upload.php)
         echo "Server response: $response"
         if [[ "$response" != *"File uploaded successfully."* ]]; then
           echo 'Failed to deploy to local server'
